services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  orderservice:
    image: tseromomenti/orderservice:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Azure
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - rabbitmq

  inventoryservice-api:
    image: tseromomenti/inventoryservice-api:latest
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    depends_on:
      - mongodb
      - redis

  inventoryservice-worker:
    image: tseromomenti/inventoryservice-worker:latest
    environment:
      - DOTNET_ENVIRONMENT=Release
    depends_on:
      - mongodb
      - redis
      - rabbitmq

  apigateway:
    image: tseromomenti/apigateway:latest
    ports:
      - "9000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    depends_on:
      - orderservice
      - inventoryservice-worker
      - inventoryservice-api
      - seq
