# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ecommerceorderservice

on:
  push:
    branches:
      - master
    paths:
      - 'OrderService/**'
      - 'Ecommerce.Library/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish OrderService/OrderService.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./deployment

      - name: List deployment files
        run: |
          echo "Files in deployment folder:"
          ls -la ./deployment/ || dir ./deployment\
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: azurecloud
          audience: api://AzureADTokenExchange
          enable-AzPSSession: false

      - name: Verify Azure context and resources
        run: |
          echo "Current subscription:"
          az account show --query "{subscriptionId:id, name:name, tenantId:tenantId}" -o table
          echo "Looking for App Service 'ecommerceorderservice':"
          az webapp list --query "[?name=='ecommerceorderservice'].{Name:name, ResourceGroup:resourceGroup, State:state, Location:location}" -o table || echo "App Service not found in current subscription"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecommerceorderservice'
          slot-name: 'Production'
          resource-group-name: 'ecommerce'
          package: ./deployment
          